export const HADISTS = [
  {
    "title": "Hadis tentang Kepemimpinan sebagai Perisai Umat",
    "arabic": "حَدَّثَنَا أَبُو الْيَمَانِ: أَخْبَرَنَا شُعَيْبٌ: حَدَّثَنَا أَبُو الزِّنَادِ: أَنَّ الْأَعْرَجَ حَدَّثَهُ: أَنَّهُ سَمِعَ أَبَا هُرَيْرَةَ رضي الله عنه: أَنَّهُ سَمِعَ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ: (نَحْنُ الْآخِرُونَ السَّابِقُونَ). وَبِهَذَا الْإِسْنَادِ: (‌مَنْ ‌أَطَاعَنِي ‌فَقَدْ ‌أَطَاعَ ‌اللَّهَ، وَمَنْ عَصَانِي فَقَدْ عَصَى اللَّهَ، وَمَنْ يُطِعِ الْأَمِيرَ فَقَدْ أَطَاعَنِي، وَمَنْ يَعْصِ الْأَمِيرَ فَقَدْ عَصَانِي، وَإِنَّمَا الْإِمَامُ جُنَّةٌ، يُقَاتَلُ مِنْ وَرَائِهِ وَيُتَّقَى بِهِ، فَإِنْ أَمَرَ بِتَقْوَى اللَّهِ وَعَدَلَ فَإِنَّ لَهُ بِذَلِكَ أَجْرًا، وَإِنْ قَالَ بِغَيْرِهِ فَإِنَّ عَلَيْهِ مِنْهُ)",
    "translation": "Telah menceritakan kepada kami Abu Al-Yaman, ia berkata: Telah mengabarkan kepada kami Syu'aib, ia berkata: Telah menceritakan kepada kami Abu Az-Zinad, dari Al-A'raj, bahwa ia mendengar Abu Hurairah radhiyallahu ‘anhu berkata: Bahwa ia mendengar Rasulullah ﷺ bersabda: \"Kita adalah umat terakhir, tetapi yang pertama masuk surga.\" Dan dengan sanad ini juga disebutkan bahwa Rasulullah ﷺ bersabda: \"Barang siapa menaati aku, maka sungguh ia telah menaati Allah, dan barang siapa mendurhakaiku, maka sungguh ia telah mendurhakai Allah. Barang siapa menaati pemimpin, maka sungguh ia telah menaati aku, dan barang siapa mendurhakai pemimpin, maka sungguh ia telah mendurhakaiku. Sesungguhnya imam (pemimpin) adalah perisai, di belakangnya orang-orang berperang dan dengannya mereka mencari perlindungan. Jika ia memerintahkan untuk bertakwa kepada Allah dan berlaku adil, maka baginya pahala. Namun, jika ia berkata selain itu (bertindak zalim), maka ia akan mendapatkan dosa akibatnya.\"",
    "source": "HR. Bukhari, no. 2957"
  },
  {
    "title": "Hadis tentang Keutamaan Pemimpin yang Adil",
    "arabic": "حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ وَزُهَيْرُ بْنُ حَرْبٍ وَابْنُ نُمَيْرٍ. قَالُوا: حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ عَنْ عَمْرٍو (يَعْنِي ابْنَ دِينَار)، عَنْ عَمْرِو بْنِ أَوْسٍ، عَنْ عَبْدِ اللَّهِ بْنِ عَمْرٍو. قَالَ ابْنُ نُمَيْرٍ وَأَبُو بَكْرٍ: يَبْلُغُ بِهِ النَّبِيَّ ﷺ. وَفِي حَدِيثِ زُهَيْرٍ قَالَ: قَالَ رَسُولُ اللَّهِ ﷺ: (إِنَّ الْمُقْسِطِينَ، عِندَ اللَّهِ، عَلَى مَنَابِرَ مِنْ نُورٍ، عَنْ يَمِينِ الرَّحْمَنِ عَزَّ وَجَلَّ، وَكِلْتَا يَدَيْهِ يَمِينٌ؛ الَّذِينَ يَعْدِلُونَ فِي حُكْمِهِمْ وَأَهْلِيهِمْ وَمَا وَلُوا)",
    "translation": "Telah menceritakan kepada kami Abu Bakr bin Abi Syaibah, Zuhair bin Harb, dan Ibnu Numair, mereka berkata: Telah menceritakan kepada kami Sufyan bin Uyainah, dari Amr (yaitu Ibnu Dinar), dari Amr bin Aus, dari Abdullah bin Amr. Ibnu Numair dan Abu Bakr mengatakan bahwa hadis ini bersumber dari Nabi ﷺ. Sedangkan dalam riwayat Zuhair, ia berkata: Rasulullah ﷺ bersabda: \"Sesungguhnya orang-orang yang berlaku adil akan berada di atas mimbar-mimbar dari cahaya di sisi kanan Allah Yang Maha Pengasih. Dan kedua tangan-Nya adalah kanan. Mereka adalah orang-orang yang berlaku adil dalam hukum mereka, terhadap keluarga mereka, dan terhadap siapa pun yang berada di bawah kepemimpinan mereka.\"",
    "source": "HR. Muslim No. 1827"
  },
  {
    "title": "Hadis tentang Larangan Memberontak kepada Pemimpin yang Sah",
    "arabic": "حَدَّثَنَا عُبَيْدُ اللَّهِ بْنُ مُعَاذٍ الْعَنْبَرِيُّ. حَدَّثَنَا أَبِي. حَدَّثَنَا عَاصِمٌ (وَهُوَ ابْنُ مُحَمَّدِ بْنِ زَيْدٍ) عَنْ زَيْدِ بْنِ مُحَمَّدٍ، عَنْ نَافِعٍ. قَالَ: جَاءَ عَبْدُ اللَّهِ بْنُ عُمَرَ إِلَى عَبْدِ اللَّهِ بْنِ مُطِيعٍ، حِينَ كَانَ مِنْ أَمْرِ الْحَرَّةِ مَا كَانَ، زَمَنَ يَزِيدَ بْنِ مُعَاوِيَةَ. فَقَالَ: اطْرَحُوا لِأَبِي عَبْدِ الرَّحْمَنِ وِسَادَةً. فَقَالَ: إِنِّي لَمْ آتِكَ لِأَجْلِسَ. أَتَيْتُكَ لِأُحَدِّثَكَ حَدِيثًا سَمِعْتُ رَسُولَ اللَّهِ ﷺ يَقُولُهُ. سَمِعْتُ رَسُولَ اللَّهِ ﷺ يَقُولُ: (مَنْ خَلَعَ يَدًا مِنْ طَاعَةٍ، لَقِيَ اللَّهَ يَوْمَ الْقِيَامَةِ، لَا حُجَّةَ لَهُ. وَمَنْ مَاتَ وَلَيْسَ فِي عُنُقِهِ بَيْعَةٌ، مَاتَ مِيتَةً جَاهِلِيَّةً)",
    "translation": "Telah menceritakan kepada kami Ubaidullah bin Mu'adz Al-Anbari, ia berkata: Telah menceritakan kepada kami ayahku, ia berkata: Telah menceritakan kepada kami Ashim (yaitu Ibnu Muhammad bin Zaid) dari Zaid bin Muhammad, dari Nafi', ia berkata: Abdullah bin Umar datang kepada Abdullah bin Muti’, ketika terjadi peristiwa Al-Harrah pada masa Yazid bin Mu'awiyah. Abdullah bin Muti’ berkata: \"Letakkan bantal untuk Abu Abdurrahman (Abdullah bin Umar).\" Namun, Abdullah bin Umar berkata: \"Aku tidak datang kepadamu untuk duduk, tetapi aku datang untuk menyampaikan sebuah hadis yang aku dengar dari Rasulullah ﷺ.\" Aku mendengar Rasulullah ﷺ bersabda: \"Barang siapa yang melepaskan tangannya dari ketaatan (kepada pemimpin yang sah), maka ia akan menemui Allah pada hari kiamat dalam keadaan tanpa memiliki hujjah (alasan yang sah). Dan barang siapa mati dalam keadaan tidak memiliki baiat (kepada pemimpin Muslim), maka ia mati dalam keadaan jahiliyah.\"",
    "source": "HR. Muslim No. 1851"
  },
  {
    "title": "Hadis tentang Pemimpin yang Menyulitkan Rakyatnya",
    "arabic": "حدثني هارون بن سعيد الأيلي. حدثنا ابن وَهْبٍ. حَدَّثَنِي حَرْمَلَةُ عَنْ عَبْدِ الرَّحْمَنِ بْنِ شِمَاسَةَ. قَالَ: أَتَيْتُ عَائِشَةَ أَسْأَلُهَا عَنْ شَيْءٍ. فَقَالَتْ: مِمَّنْ أَنْتَ؟ فَقُلْتُ: رَجُلٌ مِنْ أَهْلِ مِصْرَ. فَقَالَتْ: كَيْفَ كَانَ صَاحِبُكُمْ لَكُمْ فِي غَزَاتِكُمْ هَذِهِ؟ فَقَالَ: مَا نَقَمْنَا مِنْهُ شَيْئًا. إِنْ كَانَ لَيَمُوتُ لِلرَّجُلِ مِنَّا الْبَعِيرُ، فَيُعْطِيهِ الْبَعِيرَ. وَالْعَبْدُ، فَيُعْطِيهِ الْعَبْدَ. وَيَحْتَاجُ إِلَى النَّفَقَةِ، فَيُعْطِيهِ النَّفَقَةَ. فَقَالَتْ: أَمَا إِنَّهُ لَا يَمْنَعُنِي الَّذِي فَعَلَ فِي مُحَمَّدِ بْنِ أَبِي بَكْرٍ، أَخِي، أَنْ أُخْبِرَكَ مَا سَمِعْتُ مِنْ رَسُولِ اللَّهِ ﷺ، يَقُولُ فِي بَيْتِي هَذَا: (اللَّهُمَّ! مَنْ وَلِيَ مِنْ أَمْرِ أُمَّتِي شَيْئًا فَشَقَّ عَلَيْهِمْ، فَاشْقُقْ عَلَيْهِ. وَمَنْ وَلِيَ مِنْ أَمْرِ أُمَّتِي شَيْئًا فَرَفَقَ بِهِمْ، فارفق به)",
    "translation": "Telah menceritakan kepadaku Harun bin Sa'id Al-Ayli, telah menceritakan kepada kami Ibnu Wahb, telah menceritakan kepadaku Harmalah, dari Abdurrahman bin Syimasah, ia berkata: 'Aku datang kepada Aisyah (radhiyallahu ‘anha) untuk bertanya sesuatu. Maka ia berkata kepadaku: 'Dari mana asalmu?' Aku menjawab, 'Aku seorang laki-laki dari penduduk Mesir.' Lalu Aisyah bertanya: 'Bagaimana sikap pemimpin kalian terhadap kalian dalam peperangan ini?' Aku menjawab: 'Kami tidak melihat sesuatu yang buruk darinya. Jika ada seseorang dari kami yang untanya mati, maka ia memberinya unta. Jika ada yang kehilangan budaknya, maka ia memberinya budak. Jika ada yang membutuhkan nafkah, maka ia memberinya nafkah.' Kemudian Aisyah berkata: 'Apa yang ia lakukan terhadap Muhammad bin Abu Bakar (saudaraku) tidak menghalangiku untuk menyampaikan kepadamu apa yang pernah aku dengar dari Rasulullah ﷺ, yang beliau ucapkan di rumah ini.' Rasulullah ﷺ bersabda: 'Ya Allah, siapa saja yang mengurus urusan umatku lalu menyulitkan mereka, maka persulitlah dia. Dan siapa saja yang mengurus urusan umatku lalu berlaku lembut kepada mereka, maka berlaku lembutlah kepadanya.'",
    "source": "HR. Muslim No. 1828"
  },
  {
    "title": "Hadis tentang Tanggung Jawab Hakim dalam Mengambil Keputusan",
    "arabic": "حَدَّثَنَا مُحَمَّدُ بْنُ إِسْمَاعِيلَ، قَالَ: حَدَّثَنِي الْحَسَنُ بْنُ بِشْرٍ، قَالَ: حَدَّثَنَا شَرِيكٌ، عَنِ الْأَعْمَشِ، عَنْ سَعْدِ بْنِ عُبَيْدَةَ، عَنِ ابْنِ بُرَيْدَةَ، عَنْ أَبِيهِ، أَنَّ النَّبِيَّ ﷺ قَالَ: «الْقُضَاةُ ثَلَاثَةٌ، قَاضِيَانِ فِي النَّارِ وَقَاضٍ فِي الْجَنَّةِ»: رَجُلٌ قَضَى بِغَيْرِ الْحَقِّ فَعَلِمَ ذَاكَ، فَذَاكَ فِي النَّارِ، وَقَاضٍ لَا يَعْلَمُ فَأَهْلَكَ حُقُوقَ النَّاسِ فَهُوَ فِي النَّارِ، وَقَاضٍ قَضَى بِالْحَقِّ فَذَلِكَ فِي الْجَنَّةِ.",
    "translation": "Telah menceritakan kepada kami Muhammad bin Isma'il, ia berkata: Telah menceritakan kepadaku Al-Hasan bin Bisyr, ia berkata: Telah menceritakan kepada kami Syarik, dari Al-A'masy, dari Sa'd bin Ubaidah, dari Ibnu Buraidah, dari ayahnya (Buraidah) bahwa Nabi ﷺ bersabda: \"Para hakim (qadhi) itu ada tiga jenis: dua di neraka, dan satu di surga. • Seorang hakim yang memutuskan perkara dengan tidak benar, sedangkan ia tahu itu salah — maka ia di neraka. • Seorang hakim yang tidak tahu (bodoh) lalu menghancurkan hak-hak manusia — maka ia juga di neraka. • Dan seorang hakim yang memutuskan perkara dengan kebenaran — maka ia di surga.\"",
    "source": "HR. Tirmidzi No. 1322"
  },
  {
    "title": "Hadis tentang Hukuman Bagi Pejabat yang Korupsi",
    "arabic": "حَدَّثَنَا أَبُو مُوسَى مُحَمَّدُ بْنُ الْمُثَنَّى، قَالَ: حَدَّثَنَا أَبُو عَامِرٍ الْعَقَدِيُّ، قَالَ: حَدَّثَنَا ابْنُ أَبِي ذِئْبٍ، عَنْ خَالِهِ الْحَارِثِ بْنِ عَبْدِ الرَّحْمَنِ، عَنْ أَبِي سَلَمَةَ، عَنْ عَبْدِ اللهِ بْنِ عَمْرٍو قَالَ: «لَعَنَ رَسُولُ اللهِ صلى الله عليه وسلم ‌الرَّاشِيَ وَالْمُرْتَشِيَ هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ.»",
    "translation": "Telah menceritakan kepada kami Abu Musa Muhammad bin Al-Mutsanna, ia berkata: Telah menceritakan kepada kami Abu Amir Al-Aqadi, ia berkata: Telah menceritakan kepada kami Ibnu Abi Dzi’b, dari pamannya Al-Harits bin Abdurrahman, dari Abu Salamah, dari Abdullah bin Amr, ia berkata: \"Rasulullah ﷺ melaknat pemberi suap dan penerima suap.\" Hadis ini hasan sahih.",
    "source": "HR. Tirmidzi No. 1337"
  },
  {
    "title": "Hadis tentang Larangan Meminta Jabatan",
    "arabic": "حَدَّثَنَا أَبُو النُّعْمَانِ مُحَمَّدُ بْنُ الْفَضْلِ: حَدَّثَنَا جَرِيرُ بْنُ حَازِمٍ: حَدَّثَنَا الْحَسَنُ: حَدَّثَنَا عَبْدُ الرَّحْمَنِ بْنُ سَمُرَةَ قَالَ: قَالَ لِي النَّبِيُّ صلى الله عليه وسلم: (يَا عَبْدَ الرَّحْمَنِ بْنَ سَمُرَةَ، ‌لَا ‌تَسْأَلِ ‌الْإِمَارَةَ، فَإِنَّكَ إِنْ أُوتِيتَهَا عَنْ مَسْأَلَةٍ وُكِلْتَ إِلَيْهَا، وَإِنْ أُوتِيتَهَا مِنْ غَيْرِ مَسْأَلَةٍ أُعِينْتَ عَلَيْهَا).",
    "translation": "Telah menceritakan kepada kami Abu Nu'man Muhammad bin Al-Fadhl, telah menceritakan kepada kami Jarir bin Hazim, telah menceritakan kepada kami Al-Hasan, telah menceritakan kepada kami Abdurrahman bin Samurah, ia berkata: Rasulullah ﷺ bersabda kepadaku: \"Wahai Abdurrahman bin Samurah, janganlah engkau meminta jabatan. Karena sesungguhnya jika engkau diberi jabatan karena permintaanmu, maka engkau akan diserahkan (untuk mengurusnya) sendiri. Tetapi jika engkau diberi jabatan tanpa permintaan, maka engkau akan diberi pertolongan (oleh Allah) dalam menjalankannya.\"",
    "source": "HR. Bukhori No. 6248"
  },
  {
    "title": "Hadis tentang Ketika Sudah Jadi Pemimpin, Jangan Berkhianat",
    "arabic": "عَنْ أَبِي حُمَيْدٍ السَّاعِدِيِّ رَضِيَ اللهُ عَنْهُ قَالَ: اسْتَعْمَلَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ رَجُلاً مِنْ اْلأَزْدِ يُقَالُ لَهُ ابْنُ اْلُتْبِيَّةِ عَلَى الصَّدَقَةِ فَلَمَّا قَدِمَ قَالَ هَذَا لَكُمْ وَهَذَا أُهْدِيَ لِي قَالَ: فَهَلاَّ جَلَسَ فِي بَيْتِ أَبِيهِ أَوْ بَيْتِ أُمِّهِ فَيَنْظُرَ يُهْدَى لَهُ أَمْ لاَ وَالَّذِي نَفْسِي بِيَدِهِ لاَ يَأْخُذُ أَحَدٌ مِنْهُ شَيْئًا إِلاَّ جَاءَ بِهِ يَوْمَ الْقِيَامَةِ يَحْمِلُهُ عَلَى رَقَبَتِهِ إِنْ كَانَ بَعِيرًا لَهُ رُغَاءٌ أَوْ بَقَرَةً لَهَا خُوَارٌ أَوْ شَاةً تَيْعَرُ ثُمَّ رَفَعَ بِيَدِهِ حَتَّى رَأَيْنَا عُفْرَةَ إِبْطَيْهِ اللَّهُمَّ هَلْ بَلَّغْتُ اللَّهُمَّ هَلْ بَلَّغْتُ ثَلاَثًا.",
    "translation": "Dari Abi Humaid al-Sa’id ra: Nabi saw pernah mengangkat Ibnu Lutbiyah, yaitu seorang laki-laki dari al-Azdi (menjadi seorang pegawai), untuk memungut zakat, kemudian dia datang kepada Nabi saw dan menyerahkan zakat yang dipungutnya, lalu dia berkata, 'Ini adalah zakat yang aku setorkan kepada anda, dan ini adalah pemberian orang kepadaku.' Kemudian beliau bersabda: 'Mengapa dia tidak duduk saja di rumah ibu bapaknya sambil menunggu apakah ada orang yang hendak mengantarkan hadiah kepadanya ataukah tidak. Dan demi Dzat yang jiwaku di tangan-Nya, tidak seorangpun yang mengambil sesuatu dari zakat kecuali dia akan datang pada hari kiamat dengan dipikulkan di atas lehernya berupa unta yang berteriak, atau sapi yang melembuh, atau kambing yang mengembik.' Kemudian beliau mengangkat tangan beliau sehingga terlihat oleh kami ketiak beliau yang putih dan (berkata,): 'Ya Allah bukankah aku sudah sampaikan, bukankah aku sudah sampaikan ….' sebanyak tiga kali.",
    "source": "HR. Al-Bukhari No. 2407"
  },
  {
    "title": "Hadis tentang Alasan Rasulullah saw tidak membolehkan meminta jabatan",
    "arabic": "عن عَبْدُ الرَّحْمَنِ بْنُ سَمُرَةَ قَالَ: قَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: يَا عَبْدَ الرَّحْمَنِ بْنَ سَمُرَةَ لاَ تَسْأَلْ اْلإِمَارَةَ فَإِنَّكَ إِنْ أُوتِيتَهَا عَنْ مَسْأَلَةٍ وُكِلْتَ إِلَيْهَا وَإِنْ أُوتِيتَهَا مِنْ غَيْرِ مَسْأَلَةٍ أُعِينْتَ عَلَيْهَا وَإِذَا حَلَفْتَ عَلَى يَمِينٍ فَرَأَيْتَ غَيْرَهَا خَيْرًا مِنْهَا فَكَفِّرْ عَنْ يَمِينِكَ وَأْتِ الَّذِي هُوَ خَيْرٌ.",
    "translation": "Dari Abdurrahman ibn Samurah berkata: Nabi saw bersabda: 'Wahai Abdurrahman ibn Samurah, Janganlah kamu meminta jabatan, sebab jika engkau diberi (jabatan) karena meminta, kamu akan ditelantarkan, dan jika kamu diberi dengan tidak meminta, kamu akan ditolong, dan jika kamu melakukan sumpah, kemudian kamu melihat suatu yang lebih baik, bayarlah kaffarat sumpahmu dan lakukanlah yang lebih baik.'",
    "source": "HR. Sahih al-Bukhari No. 6132; Sahih Muslim No. 3401"
  },
  {
    "title": "Hadis tentang Jangan memilih Wakil yang lemah",
    "arabic": "عَنْ أَبِي ذَرٍّ قَالَ: قُلْتُ: يَا رَسُولَ اللهِ أَلاَ تَسْتَعْمِلُنِي قَالَ: فَضَرَبَ بِيَدِهِ عَلَى مَنْكِبِي ثُمَّ قَالَ: يَا أَبَا ذَرٍّ إِنَّكَ ضَعِيفٌ وَإِنَّهَا أَمَانَةُ وَإِنَّهَا يَوْمَ الْقِيَامَةِ خِزْيٌ وَنَدَامَةٌ إِلاَّ مَنْ أَخَذَهَا بِحَقِّهَا وَأَدَّى الَّذِي عَلَيْهِ فِيهَا.",
    "translation": "Dari Abu Dzar berkata, saya berkata: Wahai Rasulullah, tidakkah anda menjadikanku sebagai pegawai (pejabat)? Abu Dzar berkata: Kemudian beliau menepuk bahuku dengan tangan beliau seraya bersabda: 'Wahai Abu Dzar, kamu ini lemah (untuk memegang jabatan) padahal jabatan merupakan amanah. Pada hari kiamat ia adalah kehinaan dan penyesalan, kecuali bagi siapa yang mengambilnya dengan haq dan melaksanakan tugas dengan benar.'",
    "source": "HR. Sahih Muslim No. 3404 dan 3405"
  },
  {
    "title": "Hadis tentang Jangan memilih orang yang memusuhi umat Islam",
    "arabic": "عَنْ ابْنِ عُمَرَ أَنَّ النَّبِيَّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ قَالَ : مَنْ حَمَلَ عَلَيْنَا السِّلاَحَ فَلَيْسَ مِنَّا.",
    "translation": "Dari Ibn Umar ra bahwa Nabi saw bersabda: Barangsiapa membawa pedang untuk menyerang kami, maka dia bukan dari golongan kami.",
    "source": "HR. Sahih al-Bukhari No. 6366; Sahih Muslim No. 143"
  },
  {
    "title": "Doa Pemimpin yang adil jadi mustajab",
    "arabic": "عَنْ أَبِي هُرَيْرَةَ قَالَ: قَالَ رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: ثَلاَثَةٌ لاَ تُرَدُّ دَعْوَتُهُمْ الصَّائِمُ حَتَّى يُفْطِرَ وَالْإِمَامُ الْعَادِلُ وَدَعْوَةُ الْمَظْلُومِ يَرْفَعُهَا اللهُ فَوْقَ الْغَمَامِ وَيَفْتَحُ لَهَا أَبْوَابَ السَّمَاءِ وَيَقُولُ الرَّبُّ وَعِزَّتِي لأَنْصُرَنَّكِ وَلَوْ بَعْدَ حِينٍ.",
    "translation": "Dari Abu Hurairah berkata: Rasulullah saw bersabda: 'Tiga orang yang do’a mereka tidak tertolak, yaitu; seorang yang berpuasa hingga berbuka, seorang imam (penguasa) yang adil dan do’anya orang yang dizalimi. Allah akan mengangkat do’anya ke atas awan, dan membukakan baginya pintu-pintu langit, seraya berfirman: Demi kemuliaan-Ku, sungguh Aku akan menolongmu meski beberapa saat lamanya.'",
    "source": "HR. al-Tirmizi No. 3522; Ibn Majah No. 1742. Al-Tirmizi berkata: Hadis ini hasan."
  },
  {
    "title": "Pemimpin yang adil akan ditolong Allah",
    "arabic": "عَنْ عَبْدِ الرَّحْمَنِ بْنِ شِمَاسَةَ قَالَ أَتَيْتُ عَائِشَةَ أَسْأَلُهَا عَنْ شَيْءٍ فَقَالَتْ: مِمَّنْ أَنْتَ ؟ فَقُلْتُ : رَجُلٌ مِنْ أَهْلِ مِصْرَ . فَقَالَتْ :كَيْفَ كَانَ صَاحِبُكُمْ لَكُمْ فِي غَزَاتِكُمْ هَذِهِ فَقَالَ مَا نَقَمْنَا مِنْهُ شَيْئًا إِنْ كَانَ لَيَمُوتُ لِلرَّجُلِ مِنَّا الْبَعِيرُ فَيُعْطِيهِ الْبَعِيرَ وَالْعَبْدُ فَيُعْطِيهِ الْعَبْدَ وَيَحْتَاجُ إِلَى النَّفَقَةِ فَيُعْطِيهِ النَّفَقَةَ. فَقَالَتْ: أَمَا إِنَّهُ لاَ يَمْنَعُنِي الَّذِي فَعَلَ فِي مُحَمَّدِ بْنِ أَبِي بَكْرٍ أَخِي أَنْ أُخْبِرَكَ مَا سَمِعْتُ مِنْ رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ يَقُولُ فِي بَيْتِي: هَذَا اللَّهُمَّ مَنْ وَلِيَ مِنْ أَمْرِ أُمَّتِي شَيْئًا فَشَقَّ عَلَيْهِمْ فَاشْقُقْ عَلَيْهِ وَمَنْ وَلِيَ مِنْ أَمْرِ أُمَّتِي شَيْئًا فَرَفَقَ بِهِمْ فَارْفُقْ بِهِ.",
    "translation": "Dari Abdurrahman ibn Syimasah berkata: Saya mendatangi ‘Aisyah untuk menanyakan tentang sesuatu, maka dia balik bertanya: Dari manakah kamu? Saya menjawab: Seorang dari penduduk Mesir. Aisyah berkata: Bagaimana keadaan sahabat kalian yang berperang bersama kalian dalam peperangan ini? Dia menjawab: Kami tidak pernah membencinya sedikitpun, jika keledai salah seorang dari kami mati maka dia menggantinya, jika yang mati budak maka dia akan mengganti seorang budak, dan jika salah seorang dari kami membutuhkan kebutuhan hidup maka ia akan memberinya. ‘Aisyah berkata: Tidak layak bagiku jika saya tidak mengutarakan keutamaan saudaraku, Muhammad ibn Abu Bakar, saya akan memberitahukanmu sesuatu yang pernah saya dengar dari Rasulullah saw. Beliau berdo’a ketika berada di rumahku ini: Ya Allah, siapa yang menjabat suatu jabatan dalam pemerintahan ummatku lalu dia mempersulit urusan mereka, maka persulitlah dia. Dan siapa yang menjabat suatu jabatan dalam pemerintahan ummatku lalu dia berusaha menolong mereka, maka tolong pulalah dia.",
    "source": "HR. Sahih Muslim No. 3407"
  },
  {
    "title": "Pemimpin Adil Akan Dinaungi dari Terik Panas Padang Makhsyar",
    "arabic": "عَنْ أَبِي هُرَيْرَةَ عَنْ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ قَالَ: سَبْعَةٌ يُظِلُّهُمْ اللهُ فِي ظِلِّهِ يَوْمَ لاَ ظِلَّ إِلَّا ظِلُّهُ اْلإِمَامُ الْعَادِلُ وَشَابٌّ نَشَأَ فِي عِبَادَةِ رَبِّهِ وَرَجُلٌ قَلْبُهُ مُعَلَّقٌ فِي الْمَسَاجِدِ وَرَجُلاَنِ تَحَابَّا فِي اللهِ اجْتَمَعَا عَلَيْهِ وَتَفَرَّقَا عَلَيْهِ وَرَجُلٌ طَلَبَتْهُ امْرَأَةٌ ذَاتُ مَنْصِبٍ وَجَمَالٍ فَقَالَ إِنِّي أَخَافُ اللهَ وَرَجُلٌ تَصَدَّقَ أَخْفَى حَتَّى لاَ تَعْلَمَ شِمَالُهُ مَا تُنْفِقُ يَمِينُهُ وَرَجُلٌ ذَكَرَ اللهَ خَالِيًا فَفَاضَتْ عَيْنَاهُ.",
    "translation": "Telah menceritakan kepada kami Muhammad bin Basysyar Bundar berkata, telah menceritakan kepada kami Yahya dari ‘Ubaidullah berkata, telah menceritakan kepadaku Khubaib bin ‘Abdurrahman dari Hafsh bin ‘Ashim dari Abu Hurairah dari Nabi shallallahu ‘alaihi wasallam bersabda: Ada tujuh golongan manusia yang akan mendapat naungan Allah pada hari yang tidak ada naungan kecuali naungan-Nya; pemimpin yang adil, seorang pemuda yang menyibukkan dirinya dengan ‘ibadah kepada Rabbnya, seorang laki-laki yang hatinya terpaut dengan masjid, dua orang laki-laki yang saling mencintai karena Allah; mereka tidak bertemu kecuali karena Allah dan berpisah karena Allah, seorang laki-laki yang diajak berbuat maksiat oleh seorang wanita kaya lagi cantik lalu dia berkata, ‘Aku takut kepada Allah’, dan seorang yang bersedekah dengan menyembunyikannya hingga tangan kirinya tidak mengetahui apa yang diinfakkan oleh tangan kanannya, serta seorang laki-laki yang berdzikir kepada Allah dengan mengasingkan diri hingga kedua matanya basah karena menangis.",
    "source": "HR. Sahih al-Bukhari No. 620; Sahih Muslim No. 172"
  },
  {
    "title": "Pemimpin Adil Akan Mendapatkan Mimbar dari Cahaya",
    "arabic": "عَنْ عَبْدِ اللهِ بْنِ عَمْرٍو قَالَ: قَالَ رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ : إِنَّ الْمُقْسِطِينَ عِنْدَ اللهِ عَلَى مَنَابِرَ مِنْ نُورٍ عَنْ يَمِينِ الرَّحْمَنِ عَزَّ وَجَلَّ وَكِلْتَا يَدَيْهِ يَمِينٌ الَّذِينَ يَعْدِلُونَ فِي حُكْمِهِمْ وَأَهْلِيهِمْ وَمَا وَلُوا.",
    "translation": "Dari Abdullah ibn ‘Amru berkata: Rasulullah saw bersabda: Orang-orang yang berlaku adil berada di sisi Allah di atas mimbar (panggung) yang terbuat dari cahaya, di sebelah kanan Ar Rahman ‘azza wajalla -sedangkan kedua tangan Allah adalah kanan semua-, yaitu orang-orang yang berlaku adil dalam hukum, adil dalam keluarga dan adil dalam melaksanakan tugas yang di bebankan kepada mereka.",
    "source": "HR. Sahih Muslim No. 3406"
  },
  {
    "title": "Akan Menjadi Orang yang Paling Dicintai dan Paling Dekat dengan Allah",
    "arabic": "عَنْ أَبِي سَعِيدٍ قَالَ: قَالَ رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ : إِنَّ أَحَبَّ النَّاسِ إِلَى اللهِ يَوْمَ الْقِيَامَةِ وَأَدْنَاهُمْ مِنْهُ مَجْلِسًا إِمَامٌ عَادِلٌ وَأَبْغَضَ النَّاسِ إِلَى اللهِ وَأَبْعَدَهُمْ مِنْهُ مَجْلِسًا إِمَامٌ جَائِرٌ.",
    "translation": "Dari Abu Sa’id berkata: Rasulullah saw bersabda: Sesungguhnya manusia yang paling dicintai oleh Allah dan paling dekat tempat duduknya pada hari kiamat adalah pemimpin yang adil, sedangkan manusia paling dibenci oleh Allah dan paling jauh tempat duduknya adalah pemimpin yang zhalim.",
    "source": "HR. al-Tirmizi, hadis no. 1250; Ahmad, hadis no. 10745 dan 1109."
  },
  {
    "title": "Ancaman Kepada Pemimpin yang Zalim",
    "arabic": "عن مَعْقِلَ بْنَ يَسَارٍ الْمُزَنِيَّ قَالَ: سَمِعْتُ رَسُولَ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ يَقُولُ: مَا مِنْ عَبْدٍ يَسْتَرْعِيهِ اللهُ رَعِيَّةً يَمُوتُ يَوْمَ يَمُوتُ وَهُوَ غَاشٌّ لِرَعِيَّتِهِ إِلاَّ حَرَّمَ اللهُ عَلَيْهِ الْجَنَّةَ.",
    "translation": "Dari Ma’qil bin Yasar Al Muzanni berkata: Sesungguhnya saya pernah mendengar Rasulullah saw bersabda: Tidaklah seorang pemimpin yang Allah serahi untuk memimpin rakyatnya, ketika meninggal dalam keadaan menipu rakyatnya, melainkan Allah akan mengharamkan surga untuknya.",
    "source": "HR. Sahih Muslim, hadis no. 3409 dan 3410."
  },
  {
    "title": "Alasan Rasulullah saw tidak membolehkan meminta jabatan",
    "arabic": "عَنْ عَبْدُ الرَّحْمَنِ بْنُ سَمُرَةَ قَالَ: قَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: يَا عَبْدَ الرَّحْمَنِ بْنَ سَمُرَةَ لاَ تَسْأَلْ اْلإِمَارَةَ فَإِنَّكَ إِنْ أُوتِيتَهَا عَنْ مَسْأَلَةٍ وُكِلْتَ إِلَيْهَا وَإِنْ أُوتِيتَهَا مِنْ غَيْرِ مَسْأَلَةٍ أُعِنْتَ عَلَيْهَا وَإِذَا حَلَفْتَ عَلَى يَمِينٍ فَرَأَيْتَ غَيْرَهَا خَيْرًا مِنْهَا فَكَفِّرْ عَنْ يَمِينِكَ وَأْتِ الَّذِي هُوَ خَيْرٌ.",
    "translation": "Dari Abdurrahman ibn Samurah berkata: Nabi saw bersabda: 'Wahai Abdurrahman ibn Samurah, Janganlah kamu meminta jabatan, sebab jika engkau diberi (jabatan) karena meminta, kamu akan ditelantarkan, dan jika kamu diberi dengan tidak meminta, kamu akan ditolong, dan jika kamu melakukan sumpah, kemudian kamu melihat suatu yang lebih baik, bayarlah kaffarat sumpahmu dan lakukanlah yang lebih baik.'",
    "source": "Sahih al-Bukhari, hadis no. 6132; Muslim, hadis no. 3401."
  },
  {
    "title": "Hadis tentang Khilafah",
    "arabic": "يا ابنَ حَوَالة، ‌إذا ‌رأيت ‌الخلافة ‌قد ‌نزلت ‌الأرض ‌المقدَّسة، فقد دَنَتِ الزلازل والبلايا والأمورُ العِظام، للسَّاعةُ يومئذٍ أقرب للناس من يدي هذه من رأسك هذا- حَدَّثَنَا أَبُو الْعَبَّاسِ مُحَمَّدُ بْنُ يَعْقُوبَ، حَدَّثَنَا هَارُونُ بْنُ سُلَيْمَانَ الْأَصْبَهَانِيُّ، ثَنَا عَبْدُ الرَّحْمَنِ بْنُ مَهْدِيٍّ، عَنْ مُعَاوِيَةَ بْنِ صَالِحٍ، عَنْ ضَمْرَةَ بْنِ حَبِيبٍ، أَنَّ ابْنَ زُغْبٍ الْإِيَادِيَّ حَدَّثَهُ، قَالَ‏:‏ نَزَلْتُ عَلَى عَبْدِ اللَّهِ بْنِ حَوَالَةَ الْأَزْدِيِّ، فَقَالَ لِي وَإِنَّهُ لَنَازِلٌ عَلَيَّ فِي بَيْتِي‏:‏ لَا أُمَّ لَكَ أَمَا يَكْفِي ابْنَ حَوَالَةَ مِائَةٌ يَجْرِي عَلَيْهِ فِي كُلِّ عَامٍ، ثُمَّ قَالَ‏:‏ بَعَثَنَا رَسُولُ اللَّهِ- صَلَّى اللَّهُ عَلَيْهِ وَآلِهِ وَسَلَّمَ- حَوْلَ الْمَدِينَةِ عَلَى أَقْدَامِنَا لِنَغْنَمَ، فَرَجَعْنَا وَلَمْ نَغْنَمْ، وَعَرَفَ الْجَهْدَ فِي وُجُوهِنَا، فَقَامَ فِينَا خَطِيبًا، فَقَالَ‏:‏ ‏\"‏ اللَّهُمَّ لَا تَكِلْهُمْ إِلَيَّ فَأَضْعُفَ عَنْهُمْ، وَلَا تَكِلْهُمْ إِلَى أَنْفُسِهِمْ فَيَعْجِزُوا عَنْهَا، وَلَا تَكِلْهُمْ إِلَى النَّاسِ فَيَسْتَأْثِرُوا عَلَيْهِمْ‏.\n‏ثُمَّ قَالَ‏:‏ ‏\"‏ لَتَفْتَحُنَّ الشَّامَ وَفَارِسَ- أَوِ الرُّومَ وَفَارِسَ- حَتَّى يَكُونَ لِأَحَدِكُمْ مِنَ الْإِبِلِ كَذَا وَكَذَا وَمِنَ الْبَقَرِ كَذَا وَكَذَا، حَتَّى يُعْطَى أَحَدُكُمْ مِائَةَ دِينَارٍ فَيَسْخَطَهَا‏.\n‏ثُمَّ وَضَعَ يَدَهُ عَلَى رَأْسِي- أَوْ عَلَى هَامَتِي-، فَقَالَ‏:‏ ‏\"‏ يَا ابْنَ حَوَالَةَ، إِذَا رَأَيْتَ الْخِلَافَةَ قَدْ نَزَلَتِ الْأَرْضَ الْمُقَدَّسَةَ فَقَدْ دَنَتِ الزَّلَازِلُ وَالْبَلَايَا وَالْأُمُورُ الْعِظَامُ، السَّاعَةُ يَوْمَئِذٍ أَقْرَبُ لِلنَّاسِ مِنْ يَدِي هَذِهِ مِنْ رَأْسِكَ ‏\"‏ ‏\"‏ هَذَا حَدِيثٌ صَحِيحُ الْإِسْنَادِ، وَلَمْ يُخْرِجَاهُ، وَعَبْدُ الرَّحْمَنِ بْنُ زُغْبٍ الْإِيَادِيُّ مَعْرُوفٌ فِي تَابِعِي أَهْلِ مِصْرَ",
    "translation": "Telah menceritakan kepada kami Abu al-Abbas Muhammad bin Ya'qub, telah menceritakan kepada kami Harun bin Sulaiman al-Asbihani, telah menceritakan kepada kami Abdurrahman bin Mahdi, dari Mu'awiyah bin Shalih, dari Damrah bin Habib, dari Ibnu Zughb al-Iyadi, yang berkata: 'Saya singgah di rumah Abdullah bin Hawaalah al-Azdi, lalu dia berkata kepada saya, 'Apa kamu tidak merasa cukup dengan seratus yang diberikan kepada kamu setiap tahun?' Kemudian dia berkata, 'Rasulullah SAW telah mengutus kami di sekitar Madinah untuk berdagang, namun kami kembali tanpa mendapatkan apa-apa, dan kesulitan terlihat di wajah kami. Maka, beliau berdiri di hadapan kami untuk berkhutbah, lalu beliau bersabda: 'Ya Allah, janganlah Engkau serahkan mereka kepadaku, lalu aku menjadi lemah terhadap mereka, dan janganlah Engkau serahkan mereka kepada diri mereka sendiri, lalu mereka menjadi lemah, dan janganlah Engkau serahkan mereka kepada manusia, sehingga mereka lebih mementingkan diri mereka sendiri daripada mereka.' Kemudian beliau bersabda, 'Pasti akan dibuka negeri Syam dan Persia, atau Romawi dan Persia, sehingga salah seorang di antara kalian akan memiliki unta sebanyak ini dan sapi sebanyak itu, bahkan akan diberikan seratus dinar kepada salah seorang dari kalian, namun dia akan merasa tidak puas.' Kemudian beliau meletakkan tangan beliau di atas kepala saya atau di atas ubun-ubun saya, lalu beliau berkata, 'Wahai Ibnu Hawaalah, apabila kamu melihat khilafah telah turun di negeri yang diberkahi (Baitul Maqdis), maka ketahuilah bahwa gempa bumi, bencana, dan peristiwa-peristiwa besar akan datang. Saat itu, waktu sudah lebih dekat bagi manusia dibandingkan dengan tangan saya yang berada di atas kepala ini.'",
    "source": "Al-Mustadrak 'ala ash-Shahihain No. Hadis No. 3227",
    "note": "Hadis ini adalah hadis yang sahih dari segi sanadnya, namun tidak dikeluarkan oleh kedua imam hadis (Bukhari dan Muslim), dan Abdurrahman bin Zughb al-Iyadi dikenal sebagai seorang tabi'in dari kalangan penduduk Mesir."
  },  
  {
    "title": "Kewajiban Menyampaikan Kebenaran kepada Penguasa Zalim",
    "arabic": "حَدَّثَنَا الْقَاسِمُ بْنُ دِينَارٍ الْكُوفِيُّ ، قَالَ: حَدَّثَنَا عَبْدُ الرَّحْمَنِ بْنُ مُصْعَبٍ أَبُو يَزِيدَ ، قَالَ: حَدَّثَنَا إِسْرَائِيلُ ، عَنْ مُحَمَّدِ بْنِ جُحَادَةَ ، عَنْ عَطِيَّةَ ، عَنْ أَبِي سَعِيدٍ الْخُدْرِيِّ، أَنَّ النَّبِيَّ صلى الله عليه وسلم قَالَ: «‌إِنَّ ‌مِنْ ‌أَعْظَمِ ‌الْجِهَادِ» ‌كَلِمَةَ ‌عَدْلٍ ‌عِنْدَ ‌سُلْطَانٍ ‌جَائِرٍ.",
    "translation": "Telah menceritakan kepada kami Al-Qasim bin Dinar Al-Kufi, ia berkata: Telah menceritakan kepada kami Abdurrahman bin Mush'ab Abu Yazid, ia berkata: Telah menceritakan kepada kami Isra'il, dari Muhammad bin Juhadah, dari Athiyyah, dari Abu Sa'id Al-Khudri radhiyallahu ‘anhu, bahwa Nabi ﷺ bersabda: 'Sesungguhnya di antara bentuk jihad yang paling agung adalah menyampaikan kalimat keadilan di hadapan penguasa yang zalim.'",
    "source": "HR Tirmidzi No. 2174, hadis hasan gharib."
  }
]