// Generated by wxt
export {}
declare global {
  const AudioPlayer: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/audio-player')['AudioPlayer']
  const ContentScriptContext: typeof import('wxt/utils/content-script-context')['ContentScriptContext']
  const Counter: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/Counter')['default']
  const DailyCeramah: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/daily-ceramah')['DailyCeramah']
  const DynamicBackground: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/dynamic-background')['DynamicBackground']
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']
  const IslamicCompanion: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/islamic-companion')['IslamicCompanion']
  const MatchPattern: typeof import('wxt/utils/match-patterns')['MatchPattern']
  const MosquesTasbih: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/mosques-tasbih')['MosquesTasbih']
  const PrayerTimes: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/prayer-times')['PrayerTimes']
  const QuranReader: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/quran-reader')['QuranReader']
  const QuranReaderModal: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/quran-reader-modal')['QuranReaderModal']
  const Tasbih: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/tasbih')['Tasbih']
  const VerseOfTheDay: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/components/verse-of-the-day')['VerseOfTheDay']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/utils/define-app-config')['defineAppConfig']
  const defineBackground: typeof import('wxt/utils/define-background')['defineBackground']
  const defineContentScript: typeof import('wxt/utils/define-content-script')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const injectScript: typeof import('wxt/utils/inject-script')['injectScript']
  const storage: typeof import('wxt/utils/storage')['storage']
  const useAppConfig: typeof import('wxt/utils/app-config')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useQuranData: typeof import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/hooks/use-quran-data')['useQuranData']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { Ayah, Surah } from '/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/hooks/use-quran-data'
  import('/Users/ridho/Documents/go/github.com/raizora/muslimfy/apps/browser-extension/hooks/use-quran-data')
}
