name: Build and Release Chrome Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to release'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Discord Build Start Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1417628415607050241/rtSDSTLV2J1YISOuuo_imuFQ6O1XolEEr7240Urt03i4nivAIiW76WLLqgpyAHUrPJds
      with:
        args: |
          🚀 **Chrome Extension Build Started!**

          📦 **Version:** ${{ github.event.inputs.version }}
          👤 **Triggered by:** ${{ github.actor }}
          🔧 **Workflow:** ${{ github.workflow }}

          ⏳ Building and preparing release...

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install

    - name: Build Chrome extension
      run: |
        pnpm --filter @muslimfy/browser-extension run build
        pnpm --filter @muslimfy/browser-extension run zip

    - name: Get package version
      id: package-version
      run: |
        cd apps/browser-extension
        echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Muslimfy Browser Extension ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Muslimfy Browser Extension Release ${{ github.event.inputs.version }}

          ### Installation Instructions:
          1. Download the `muslimfy-browser-extension-chrome.zip` file below
          2. Extract the zip file
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode" in the top right
          5. Click "Load unpacked" and select the extracted folder

          ### What's New:
          - Check the commit history for detailed changes
        files: |
          apps/browser-extension/.output/muslimfybrowser-extension-${{ steps.package-version.outputs.version }}-chrome.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension-build
        path: |
          apps/browser-extension/.output/
          !apps/browser-extension/.output/**/*.map
        retention-days: 30

    - name: Discord Success Notification
      if: success()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1417628415607050241/rtSDSTLV2J1YISOuuo_imuFQ6O1XolEEr7240Urt03i4nivAIiW76WLLqgpyAHUrPJds
      with:
        args: |
          🎉 **Chrome Extension Build & Release Successful!**

          📦 **Version:** ${{ github.event.inputs.version }}
          🏷️ **Release:** Muslimfy Browser Extension ${{ github.event.inputs.version }}
          🔗 **Release URL:** ${{ steps.create_release.outputs.url }}

          ✅ Extension has been built and uploaded to GitHub releases successfully!

    - name: Discord Failure Notification
      if: failure()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1417628415607050241/rtSDSTLV2J1YISOuuo_imuFQ6O1XolEEr7240Urt03i4nivAIiW76WLLqgpyAHUrPJds
      with:
        args: |
          ❌ **Chrome Extension Build & Release Failed!**

          📦 **Version:** ${{ github.event.inputs.version }}
          🔧 **Workflow:** ${{ github.workflow }}
          📋 **Job:** ${{ github.job }}

          ⚠️ Please check the workflow logs for more details.
          🔗 **Workflow URL:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}