name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1416205352998797516/gV7DILjx-H_hI6lowPgdUQR4hY4wJdjjKcrdIF6vg2AAtGjwOwyHST4mYnCFACUZpviU
        with:
          args: |
            🔔 **New Pull Request Opened** by ${{ github.event.pull_request.user.login }}
            
            **Details:**
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}